// locations.js
const cityData = {
    "AL": ["All Cities", "Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
    "AK": ["All Cities", "Anchorage", "Fairbanks", "Juneau"],
    "AZ": ["All Cities", "Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale"],
    "AR": ["All Cities", "Little Rock", "Fort Smith", "Fayetteville", "Springdale"],
    "CA": ["All Cities", "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside", "Stockton", "Irvine", "Chula Vista", "Fremont", "San Bernardino", "Modesto", "Fontana", "Santa Clarita", "Glendale", "Oxnard", "Moreno Valley", "Huntington Beach", "Ontario", "Rancho Cucamonga", "Santa Rosa", "Oceanside", "Elk Grove", "Garden Grove", "Pasadena"],
    "CO": ["All Cities", "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"],
    "CT": ["All Cities", "Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury"],
    "DE": ["All Cities", "Wilmington", "Dover", "Newark"],
    "DC": ["All Cities", "Washington"],
    "FL": ["All Cities", "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale"],
    "GA": ["All Cities", "Atlanta", "Augusta", "Columbus", "Macon", "Savannah"],
    "HI": ["All Cities", "Honolulu", "Hilo", "Kailua"],
    "ID": ["All Cities", "Boise", "Meridian", "Nampa", "Idaho Falls"],
    "IL": ["All Cities", "Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Springfield"],
    "IN": ["All Cities", "Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
    "IA": ["All Cities", "Des Moines", "Cedar Rapids", "Davenport", "Sioux City"],
    "KS": ["All Cities", "Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka"],
    "KY": ["All Cities", "Louisville", "Lexington", "Bowling Green", "Owensboro"],
    "LA": ["All Cities", "New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
    "ME": ["All Cities", "Portland", "Lewiston", "Bangor"],
    "MD": ["All Cities", "Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"],
    "MA": ["All Cities", "Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    "MI": ["All Cities", "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing"],
    "MN": ["All Cities", "Minneapolis", "St. Paul", "Rochester", "Duluth", "Bloomington"],
    "MS": ["All Cities", "Jackson", "Gulfport", "Southaven", "Biloxi"],
    "MO": ["All Cities", "Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
    "MT": ["All Cities", "Billings", "Missoula", "Great Falls", "Bozeman"],
    "NE": ["All Cities", "Omaha", "Lincoln", "Bellevue", "Grand Island"],
    "NV": ["All Cities", "Las Vegas", "Henderson", "Reno", "North Las Vegas"],
    "NH": ["All Cities", "Manchester", "Nashua", "Concord"],
    "NJ": ["All Cities", "Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"],
    "NM": ["All Cities", "Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe"],
    "NY": ["All Cities", "New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
    "NC": ["All Cities", "Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
    "ND": ["All Cities", "Fargo", "Bismarck", "Grand Forks", "Minot"],
    "OH": ["All Cities", "Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
    "OK": ["All Cities", "Oklahoma City", "Tulsa", "Norman", "Broken Arrow"],
    "OR": ["All Cities", "Portland", "Salem", "Eugene", "Gresham", "Hillsboro"],
    "PA": ["All Cities", "Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
    "RI": ["All Cities", "Providence", "Warwick", "Cranston", "Pawtucket"],
    "SC": ["All Cities", "Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Greenville"],
    "SD": ["All Cities", "Sioux Falls", "Rapid City", "Aberdeen"],
    "TN": ["All Cities", "Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
    "TX": ["All Cities", "Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock"],
    "UT": ["All Cities", "Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
    "VT": ["All Cities", "Burlington", "South Burlington", "Rutland"],
    "VA": ["All Cities", "Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria"],
    "WA": ["All Cities", "Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent"],
    "WV": ["All Cities", "Charleston", "Huntington", "Morgantown", "Parkersburg"],
    "WI": ["All Cities", "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
    "WY": ["All Cities", "Cheyenne", "Casper", "Laramie", "Gillette"]
};

const stateList = [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" }, { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" }, { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" }, { code: "DC", name: "District of Columbia" },
    { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" }, { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" }, { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" }, { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" }, { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" }, { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" }, { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" }, { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" }, { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" }, { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" }, { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" }, { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" }, { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" }, { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" }, { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" }
];
